// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyStudentsGrades.Models;

namespace MyStudentsGrades.Migrations
{
    [DbContext(typeof(MyStudentsGradesContext))]
    partial class MyStudentsGradesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MyStudentsGrades.Models.Classroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClassroomName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("NameSchool")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("RequiredMedia")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Classroom");
                });
#pragma warning restore 612, 618
        }
    }
}
